name: Release
on:
  release:
    types: [published]
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: python -m pip install --upgrade hatch

    - name: Build
      run: hatch build

    - name: Publish to PyPI
      run: hatch publish --user=__token__ --auth=${{ secrets.PYPI_TOKEN }}
